# Generated by Django 4.2.4 on 2024-11-20 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('link_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Name')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order of the blog')),
                ('short_description', tinymce.models.HTMLField(blank=True, default='', verbose_name='Short description')),
                ('long_description', tinymce.models.HTMLField(blank=True, default='', verbose_name='Long description')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Author')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time of publish')),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Keywords')),
                ('duration', models.IntegerField(default=5, verbose_name='Reading duration')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order of the Component')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='seo_blog.blog', verbose_name='Blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ButtonComponent',
            fields=[
                ('blogcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo_blog.blogcomponent')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Button text')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Button URL')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('seo_blog.blogcomponent',),
        ),
        migrations.CreateModel(
            name='ImageComponent',
            fields=[
                ('blogcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo_blog.blogcomponent')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Image')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('seo_blog.blogcomponent',),
        ),
        migrations.CreateModel(
            name='TextComponent',
            fields=[
                ('blogcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo_blog.blogcomponent')),
                ('content', tinymce.models.HTMLField(blank=True, default='', verbose_name='Text with HTML Tags')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('seo_blog.blogcomponent',),
        ),
        migrations.CreateModel(
            name='VideoComponent',
            fields=[
                ('blogcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seo_blog.blogcomponent')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog/videos/', verbose_name='Video')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('seo_blog.blogcomponent',),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='seo_blog.blogcategory', verbose_name='Categories'),
        ),
    ]
