# Generated by Django 4.2.4 on 2024-11-20 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Title')),
                ('hoster', models.CharField(blank=True, default='', max_length=50, verbose_name='Hoster')),
                ('hoster_description', models.CharField(blank=True, default='', max_length=50, verbose_name='Hoster description')),
                ('hoster_image', models.ImageField(blank=True, null=True, upload_to='webinars/hoster/', verbose_name='Promo image')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Short Description')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date and time')),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date and time')),
                ('attendees', models.CharField(default='99+', verbose_name='Number of attendees')),
                ('duration', models.CharField(blank=True, default='1+ hour', max_length=10, verbose_name='Duration')),
                ('promo_image', models.ImageField(blank=True, null=True, upload_to='webinars/images/', verbose_name='Promo image')),
                ('link', models.CharField(blank=True, default='', max_length=250, verbose_name='Link to webinar Zoom or video recording')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended')], default='upcoming', max_length=10, verbose_name='Status')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
