# Generated by Django 4.2.4 on 2024-11-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Dispute ID')),
                ('refunded', models.BooleanField(default=False, verbose_name='Refunded?')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('order_id', models.CharField(blank=True, default='', verbose_name='Order ID')),
            ],
        ),
        migrations.CreateModel(
            name='SolidgateUserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100, verbose_name='Solidgate user subscription ID')),
                ('card_token', models.CharField(default='', max_length=100, verbose_name='Card Token for one-click payments')),
                ('user_subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solidgate_user_subscription', to='subscription.usersubscription', verbose_name='User Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SolidgateSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_timeout_subscription_id', models.CharField(max_length=50, verbose_name='Timeout Trial subscription (product) ID')),
                ('trial_standard_subscription_id', models.CharField(max_length=50, verbose_name='Standard Trial subscription (product) ID')),
                ('trial_chase_subscription_id', models.CharField(max_length=50, verbose_name='Chase Trial subscription (product) ID')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solidgate_subscription', to='subscription.subscription', verbose_name='Our Subscription')),
            ],
        ),
        migrations.AddConstraint(
            model_name='solidgateusersubscription',
            constraint=models.UniqueConstraint(fields=('subscription_id',), name='solidgate-user-subscription--unique-constraint'),
        ),
    ]
