# Generated by Django 4.2.4 on 2024-11-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Name')),
                ('employees', models.CharField(blank=True, default='', max_length=10, verbose_name='Number of employees')),
                ('platform', models.CharField(blank=True, default='', max_length=30, verbose_name='Platform')),
                ('link', models.CharField(blank=True, default='', max_length=250, verbose_name='Link to website')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Title')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('format', models.CharField(blank=True, default='Remote', verbose_name='Format of job')),
                ('location', models.CharField(blank=True, default='Anywhere', verbose_name='Location of job')),
                ('employment', models.CharField(blank=True, default='Part-Time', verbose_name='Type of employment')),
                ('salary', models.CharField(blank=True, default='$15 000 - $25 000', verbose_name='Salary')),
                ('link', models.CharField(blank=True, default='', max_length=250, verbose_name='Apply now link')),
                ('expired', models.BooleanField(default=False, verbose_name='Expired?')),
                ('expiration_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='Expiration reason')),
                ('img', models.ImageField(blank=True, null=True, upload_to='job/', verbose_name='Image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.company', verbose_name='Company')),
                ('similar_jobs', models.ManyToManyField(blank=True, to='job.job', verbose_name='Similar jobs')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobusers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobuser',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='jobuser--job-user-unique-constraint'),
        ),
    ]
